### PR TITLE
Add support for Angular's new CommonJS standard.

### PR DESCRIPTION
**Pull request by seanhealy**

### CODE REVIEW

**Comment by rsertelon** [comment]
I guess it's retro compatible, isn't it? If so, will merge.

Thanks for your contribution.

**Comment by seanhealy** [comment]
It's following the same flow that they are using here:

https://www.npmjs.com/package/angular-animate

It shouldn't effect the other usage instructions you have. It just allows for inclusion through npm / browserify and such.

**Comment by rsertelon** [comment]
OK, perfect then :)

Again, thanks for your contribution.

**Comment by rsertelon** [comment]
Do you need a release anytime soon, or can it wait for other potential features/bugfixes for several weeks?

**Pull request merged**
